import { nanoid } from "nanoid";

export default [
  {
    id: nanoid(),
    title: "Grand Sarbon Hotel",
    category: "hotel",
    summa: "$400",
    address: "qarshi city",
    info: `Grand Sarbon Hotel has a garden, shared lounge, a terrace and Restaurants in Qarshi. The accommodation offers room service and a 24-hour front desk for guests.`,
    img: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/327044134.jpg?k=ed081cbacdd109060793e1e69737ad0ba23eb07241a52fa523536ab72821d029&o=&hp=1",
  },
  {
    id: nanoid(),
    title: "Hotel Sultan",
    category: "hotel",
    summa: "$400",
    address: "qarshi city",
    info: `Breakfast was excellent, enough to take us through the day, till the evening!!! Wonderful and attentive staff.`,
    img: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/155845321.jpg?k=f29b731d37b0256e55a7f08d20b299834d73eb1842c1c95cbdfb0f99375e6322&o=&hp=1",
  },
  {
    id: nanoid(),
    title: "Oqsaroy Hotel",
    category: "hotel",
    summa: "$400",
    address: "qarshi city",
    info: `Very attentive and caring staff. After booking, the hotel staff promptly contacted me about the parameters of the reservation, I had special requests, everything was done.`,
    img: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/382322941.jpg?k=d578388daea53670ba109cc1bf51931480fb6854b2f31782c464590a2ff561da&o=&hp=1",
  },
  {
    id: nanoid(),
    title: "Hotel Naxshab",
    category: "hotel",
    summa: "$400",
    address: "qarshi city",
    info: `The breakfasts are very tasty and varied. The buffet will suit the needs of even a capricious gourmet. `,
    img: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/163449442.jpg?k=532199b3cacc35d7d1ed65a711cf8b77126a918140e49ee8098a2e2693ddbbd8&o=&hp=1",
  },
  {
    id: nanoid(),
    title: "TASHRIF HOTEL",
    category: "hotel",
    summa: "$700",
    address: "qarshi city",
    info: `ozy, clean, modern hotel. The triple standard room was very spacious.`,
    img: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/402308424.jpg?k=caba43b1dc9d5d04c457722c31f6e392ad555c60be2b7c4b6623d1afebb4629d&o=&hp=1",
  },
  {
    id: nanoid(),
    title: "Hotel Afrosiyob",
    category: "hotel",
    summa: "$700",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/378307005.jpg?k=5d525c92d3559eeafc4479f8e93885ef63aa1f29c11a407e7964e152debba53d&o=&hp=1",
  },
  {
    id: nanoid(),
    title: "BTS EXPRESS",
    category: "pochta",
    summa: "$700",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://stat.uz/images/narx_ichi_12_10_2021.jpg",
  },
  {
    id: nanoid(),
    title: "DHL EXPRESS",
    category: "pochta",
    summa: "$5",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://stat.uz/images/narx_ichi_12_10_2021.jpg",
    tel: " 91 4682244",
  },
  {
    id: nanoid(),
    title: "DHL EXPRESS ",
    category: "pochta",
    summa: "$5",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://stat.uz/images/narx_ichi_12_10_2021.jpg",
    tel: " 91 4682244",
  },
  {
    id: nanoid(),
    title: "EMS",
    category: "pochta",
    summa: "$5",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://stat.uz/images/narx_ichi_12_10_2021.jpg",
    tel: " 91 4682244",
  },
  {
    id: nanoid(),
    title: "EMU ",
    category: "pochta",
    summa: "$5",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://stat.uz/images/narx_ichi_12_10_2021.jpg",
    tel: " 91 4682244",
  },
  {
    id: nanoid(),
    title: " POCHTASI ",
    category: "pochta",
    summa: "$5",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://stat.uz/images/narx_ichi_12_10_2021.jpg",
    tel: " 91 4682244",
  },
  {
    id: nanoid(),
    title: "STAREX",
    category: "pochta",
    summa: "$5",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://stat.uz/images/narx_ichi_12_10_2021.jpg",
    tel: " 91 4682244",
  },
  {
    id: nanoid(),
    title: "Aroma Bakery & Cafe",
    category: "Restaurants",
    summa: "$5",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://upload.wikimedia.org/wikipedia/commons/6/62/Barbieri_-_ViaSophia25668.jpg",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "Cafe Mehrangiz",
    category: "Restaurants",
    summa: "$5",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://upload.wikimedia.org/wikipedia/commons/6/62/Barbieri_-_ViaSophia25668.jpg",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "O'zbegim",
    category: "Restaurants",
    summa: "$5",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://upload.wikimedia.org/wikipedia/commons/6/62/Barbieri_-_ViaSophia25668.jpg",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "MartineZ Cocktail Bar",
    category: "Restaurants",
    summa: "$5",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://upload.wikimedia.org/wikipedia/commons/6/62/Barbieri_-_ViaSophia25668.jpg",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "Pachkamar",
    category: "Restaurants",
    summa: "$5",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://upload.wikimedia.org/wikipedia/commons/6/62/Barbieri_-_ViaSophia25668.jpg",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "KutubxonalarLAR",
    category: "Kutubxonalar",
    summa: "$1",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://static01.nyt.com/images/2022/01/16/fashion/VIRAL-LIBRARY/VIRAL-LIBRARY-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "Amerika Kutubxonalarsi",
    category: "Kutubxonalar",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://static01.nyt.com/images/2022/01/16/fashion/VIRAL-LIBRARY/VIRAL-LIBRARY-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "Kutubxonalar1",
    category: "Kutubxonalar",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://static01.nyt.com/images/2022/01/16/fashion/VIRAL-LIBRARY/VIRAL-LIBRARY-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "Kutubxonalar2",
    category: "Kutubxonalar",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://static01.nyt.com/images/2022/01/16/fashion/VIRAL-LIBRARY/VIRAL-LIBRARY-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "Kutubxonalar3",
    category: "Kutubxonalar",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://static01.nyt.com/images/2022/01/16/fashion/VIRAL-LIBRARY/VIRAL-LIBRARY-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "Kutubxonalar1",
    category: "Kutubxonalar",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://static01.nyt.com/images/2022/01/16/fashion/VIRAL-LIBRARY/VIRAL-LIBRARY-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "dom1",
    category: "Dom",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://frankfurt.apollo.olxcdn.com/v1/files/6seuac7ks9lm3-UZ/image;s=644x461",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "dom2",
    category: "Dom",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://frankfurt.apollo.olxcdn.com/v1/files/6seuac7ks9lm3-UZ/image;s=644x461",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "dom3",
    category: "Dom",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://frankfurt.apollo.olxcdn.com/v1/files/6seuac7ks9lm3-UZ/image;s=644x461",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "dom4",
    category: "Dom",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://frankfurt.apollo.olxcdn.com/v1/files/6seuac7ks9lm3-UZ/image;s=644x461",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "dom5",
    category: "Dom",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://frankfurt.apollo.olxcdn.com/v1/files/6seuac7ks9lm3-UZ/image;s=644x461",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "dom6",
    category: "Dom",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://frankfurt.apollo.olxcdn.com/v1/files/6seuac7ks9lm3-UZ/image;s=644x461",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "hovli1",
    category: "Hovli",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://frankfurt.apollo.olxcdn.com/v1/files/wmtgel7qftcd-UZ/image;s=750x1000",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "hovli2",
    category: "Hovli",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://frankfurt.apollo.olxcdn.com/v1/files/wmtgel7qftcd-UZ/image;s=750x1000",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "hovli3",
    category: "Hovli",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://frankfurt.apollo.olxcdn.com/v1/files/wmtgel7qftcd-UZ/image;s=750x1000",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "hovli4",
    category: "Hovli",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://frankfurt.apollo.olxcdn.com/v1/files/wmtgel7qftcd-UZ/image;s=750x1000",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "hovli5",
    category: "Hovli",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://frankfurt.apollo.olxcdn.com/v1/files/wmtgel7qftcd-UZ/image;s=750x1000",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "hovli6",
    category: "Hovli",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://frankfurt.apollo.olxcdn.com/v1/files/wmtgel7qftcd-UZ/image;s=750x1000",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "ish1",
    category: "Ish",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://content.mycareersfuture.gov.sg/wp-content/uploads/2021/02/job-search-singapore-2000x1334-1.png",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "ish2",
    category: "Ish",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://content.mycareersfuture.gov.sg/wp-content/uploads/2021/02/job-search-singapore-2000x1334-1.png",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "ish3",
    category: "Ish",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://content.mycareersfuture.gov.sg/wp-content/uploads/2021/02/job-search-singapore-2000x1334-1.png",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "ish4",
    category: "Ish",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://content.mycareersfuture.gov.sg/wp-content/uploads/2021/02/job-search-singapore-2000x1334-1.png",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "ish5",
    category: "Ish",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://content.mycareersfuture.gov.sg/wp-content/uploads/2021/02/job-search-singapore-2000x1334-1.png",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "ish6",
    category: "Ish",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://content.mycareersfuture.gov.sg/wp-content/uploads/2021/02/job-search-singapore-2000x1334-1.png",
    tel: " 91 99999999",
  },
  {
    id: nanoid(),
    title: "ish7",
    category: "Ish",
    summa: "$3",
    address: "qarshi city",
    info: `Хороший персонал, удобный номер с кондиционером очень хорошо. `,
    img: "https://content.mycareersfuture.gov.sg/wp-content/uploads/2021/02/job-search-singapore-2000x1334-1.png",
    tel: " 91 99999999",
  },
];
//
